name: terraform-file-run

on: 
  # push:
  #   branches:
  #     - docker_initialization
  workflow_dispatch:
    inputs: 
      steps-to-run:
        description: "select step to run "
        required: true
        default: "all"
        type: choice
        options:
          - all
          - init
          - plan
          - apply 
          - destroy



jobs:
  terraform:
    name: terraform-run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with: 
          terraform_version: 1.6.6  
      
      - name: Install Terragrunt
        run: |
            sudo apt-get update
            sudo apt-get install -y wget
            wget -qO- https://github.com/gruntwork-io/terragrunt/releases/download/v0.48.0/terragrunt_linux_amd64 > /usr/local/bin/terragrunt
            chmod +x /usr/local/bin/terragrunt

      - name: Terragrunt Init
        if: ${{github.event.inputs.steps-to-run == 'init' || github.event.inputs.steps-to-run == 'all'}}
        run: terragrunt init

      - name: Terragrunt Plan
        if: ${{github.event.inputs.steps-to-run == 'plan' || github.event.inputs.steps-to-run == 'all'}}
        run: terragrunt plan

      - name: Terragrunt Apply 
        if: ${{github.event.inputs.steps-to-run == 'apply' || github.event.inputs.steps-to-run == 'all'}}
        run: terragrunt apply -auto-approve

      - name: Terragrunt Destroy
        if: ${{github.event.inputs.steps-to-run == 'destroy' || github.event.inputs.steps-to-run == 'all'}}
        run: terragrunt destroy -auto-approve

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}