name: terraform-file-run

on:
  workflow_dispatch:
    inputs:
      Select_All:
        description: "select all steps"
        required: false
        default: false
        type: boolean
      
      Init:
        description: "initializatioonn"
        required: false
        default: false
        type: boolean
      
      Plan: 
        description: "plan"
        required: false
        default: false
        type: boolean
      
      Apply: 
        description: "apply"
        required: false
        default: false
        type: boolean
    
      Destroy:
        description: "destroy"
        required: false
        default: false
        type: boolean



jobs:
  terraform:
    name: terraform-run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
      
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v3
        with:
            terragrunt-version: 0.55.2

      - name: Terragrunt Init
        if: ${{ github.event.inputs.Init == true || github.event.inputs.Select_All == true }}
        run: terragrunt init

      - name: Terragrunt Plan
        if: ${{ github.event.inputs.Plan == true || github.event.inputs.Select_All == true }}
        run: terragrunt plan

      - name: Terragrunt Apply
        if: ${{ github.event.inputs.Apply == true || github.event.inputs.Select_All == true }}
        run: terragrunt apply -auto-approve
      
      - name: Terragrunt Destroy
        if: ${{github.event.inputs.Destroy == true || github.event.inputs.Select_All == true }}
        run: terragrunt destroy -auto-approve

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
