name: terraform-file-run

on:
  workflow_dispatch:
    inputs:
      step_to_run:
        description: "Select step to run"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - init
          - plan
          - apply
          - destroy

jobs:
  terraform:
    name: terraform-run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
      
      - name: Install Terragrunt
        run: |
            wget -q https://github.com/gruntwork-io/terragrunt/releases/latest/download/terragrunt_linux_amd64
            chmod +x terragrunt_linux_amd64
            sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
            terragrunt --version

      - name: Terragrunt Init
        if: ${{ github.event.inputs.step_to_run == 'init' || github.event.inputs.step_to_run == 'all' }}
        run: terragrunt init

      - name: Terragrunt Plan
        if: ${{ github.event.inputs.step_to_run == 'plan' || github.event.inputs.step_to_run == 'all' }}
        run: terragrunt plan

      - name: Terragrunt Apply
        if: ${{ github.event.inputs.step_to_run == 'apply' || github.event.inputs.step_to_run == 'all' }}
        run: terragrunt apply -auto-approve
      
      - name: Terragrunt Destroy
        if: ${{github.event.inputs.step_to_run == 'destroy' || github.event.inputs.step_to_run == 'all'}}
        run: terragrunt destroy -auto-approve

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
