name: terraform-file-run

on: 
  # push:
  #   branches:
  #     - docker_initialization
  workflow_dispatch:

jobs:
  terraform:
    name: terraform-run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with: 
          terraform_version: 1.6.6  

      - name: Terragrunt Init
        run: terragrunt init

      - name: Terragrunt Plan
        run: terragrunt plan

      - name: Terragrunt Apply 
        run: terragrunt apply -auto-approve

      - name: Terragrunt Destroy
        run: terragrunt destroy -auto-approve

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}